/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gio
 */
public class ComidaDialog extends javax.swing.JDialog {

    /**
     * Creates new form ComidaDialog
     */
    public ComidaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        nombretext = new javax.swing.JTextField();
        precio = new javax.swing.JLabel();
        preciotext = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        tipocombobox = new javax.swing.JComboBox<>();
        descripcion = new javax.swing.JLabel();
        descripciontext = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Nombre:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        nombretext.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jPanel1.add(nombretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 260, 30));

        precio.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setText("Precio:");
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        preciotext.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jPanel1.add(preciotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 260, 30));

        tipo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setText("Tipo:");
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        tipocombobox.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        tipocombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Plato Fuerte", "Bebida", "Postre" }));
        jPanel1.add(tipocombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 260, 30));

        descripcion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 0, 0));
        descripcion.setText("Descripcion:");
        jPanel1.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        descripciontext.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jPanel1.add(descripciontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 260, 30));

        Agregar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        eliminarBoton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Comida.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        String tipo = tipocombobox.getSelectedItem().toString();
        if (nombretext.getText().equals("") || preciotext.getText().equals("") || tipocombobox.getSelectedItem().toString().equals("") || descripciontext.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No todos los campos estan llenos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                dtoComida.setNombre(nombretext.getText());
                dtoComida.setPrecio(preciotext.getText());
                dtoComida.setTipo(tipo);
                dtoComida.setDescripcion(descripciontext.getText());
                if (Agregar.getText().equals("Agregar")) {
                    JOptionPane.showMessageDialog(this, "Comida " + dtoComida.getNombre()
                            + " registrada.",
                            "Listo", JOptionPane.INFORMATION_MESSAGE);
                    dtaComida.append(dtoComida);
                    dispose();
                } else {
                    dtaComida.update(dtoComida);
                    JOptionPane.showMessageDialog(this, "Comida " + dtoComida.getNombre()
                            + " modificada.",
                            "Listo", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        try {
            dtaComida.delete(dtoComida);
            JOptionPane.showMessageDialog(this, "Comida " + dtoComida.getNombre()
                            + " eliminada.", "Listo", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Esta se utiliza en un servicio, no se puede elminar", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarBotonActionPerformed

    public JComboBox<String> getTipocombobox() {
        return tipocombobox;
    }

    public void setTipocombobox(JComboBox<String> tipocombobox) {
        this.tipocombobox = tipocombobox;
    }

    
    public JButton getEliminarBoton() {
        return eliminarBoton;
    }

    public void setEliminarBoton(JButton eliminarBoton) {
        this.eliminarBoton = eliminarBoton;
    }

    public JButton getAgregar() {
        return Agregar;
    }

    public String getAgregarText() {
        return Agregar.getText();
    }

    public void setAgregarText(String text) {
        Agregar.setText(text);
    }

    public JTextField getDescripciontext() {
        return descripciontext;
    }

    public void setDescripciontext(JTextField descripciontext) {
        this.descripciontext = descripciontext;
    }

    public JTextField getNombretext() {
        return nombretext;
    }

    public void setNombretext(JTextField nombretext) {
        this.nombretext = nombretext;
    }

    public JTextField getPreciotext() {
        return preciotext;
    }

    public void setPreciotext(JTextField preciotext) {
        this.preciotext = preciotext;
    }

    public void setComidaDTO(ComidaDTO comida) {
        dtoComida = comida;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComidaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComidaDialog dialog = new ComidaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel background;
    private javax.swing.JLabel descripcion;
    private javax.swing.JTextField descripciontext;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombretext;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField preciotext;
    private javax.swing.JLabel tipo;
    private javax.swing.JComboBox<String> tipocombobox;
    // End of variables declaration//GEN-END:variables
    public ComidaDAO dtaComida = new ComidaDAO();
    public ComidaDTO dtoComida = new ComidaDTO();
}
