/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gio
 */
public class ConsumoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ConsumoDialog
     */
    public ConsumoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        iniciar();
    }

    private void iniciar() {
        try {
            ComidaDAO cDAO = new ComidaDAO();
            ServicioDAO sDAO = new ServicioDAO();
            ArrayList<ComidaDTO> comidas = cDAO.getAll();
            ArrayList<ServicioDTO> servicios = sDAO.getAll();
            
            for(ComidaDTO comida: comidas){
                comidaComboBox.addItem(comida.getCodigo_comida() + ": " + comida.getNombre());
            }
            
            for(ServicioDTO servicio: servicios){
                servicioComboBox.addItem(servicio.getCodigo_Servicio());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsumoDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoservicio = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        codigocomida = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        cantidadtext = new javax.swing.JTextField();
        servicioComboBox = new javax.swing.JComboBox<>();
        comidaComboBox = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoservicio.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        codigoservicio.setForeground(new java.awt.Color(0, 0, 0));
        codigoservicio.setText("Codigo Servicio:");
        jPanel1.add(codigoservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        agregar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        codigocomida.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        codigocomida.setForeground(new java.awt.Color(0, 0, 0));
        codigocomida.setText("Codigo Comida:");
        jPanel1.add(codigocomida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        cantidad.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.setText("Cantidad:");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        cantidadtext.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jPanel1.add(cantidadtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 260, 30));

        jPanel1.add(servicioComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 260, -1));

        jPanel1.add(comidaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 260, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Consumo.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (servicioComboBox.getSelectedItem().toString().equals("") || comidaComboBox.getSelectedItem().toString().equals("") || cantidadtext.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No todos los campos están llenos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                dtoConsumo.setCodigo_servicio(servicioComboBox.getSelectedItem().toString());
                String[] datos = comidaComboBox.getSelectedItem().toString().split(": ");
                dtoConsumo.setCodigo_comida(datos[0]);
                dtoConsumo.setCantidad(cantidadtext.getText());
                JOptionPane.showMessageDialog(this, "Consumo " + dtoConsumo.getCodigo_comida()
                        + " * " + dtoConsumo.getCantidad() + " registrado.",
                         "Listo", JOptionPane.INFORMATION_MESSAGE);
                dtaConsumo.append(dtoConsumo);
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsumoDialog dialog = new ConsumoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cantidad;
    private javax.swing.JTextField cantidadtext;
    private javax.swing.JLabel codigocomida;
    private javax.swing.JLabel codigoservicio;
    private javax.swing.JComboBox<String> comidaComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> servicioComboBox;
    // End of variables declaration//GEN-END:variables
    public ConsumoDAO dtaConsumo = new ConsumoDAO();
    public ConsumoDTO dtoConsumo = new ConsumoDTO();
}
