package newpackage;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gio
 */
public class ConsultaClienteDialog extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaClienteDialog
     */
    public ConsultaClienteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        // iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla.setSelectionForeground(new java.awt.Color(153, 153, 153));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 820, 280));

        buscar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        combobox.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Nombre", "Direccion", "Telefono" }));
        jPanel2.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/consultascliente.png"))); // NOI18N
        jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscar();
    }//GEN-LAST:event_buscarActionPerformed

    private void buscar(){
                try {
            model = new DefaultTableModel();
            tabla.getTableHeader().setReorderingAllowed(false);
            ArrayList<ClienteDTO> lista = dtaCliente.getAll();
            if (combobox.getSelectedIndex() == 0) {
                model.addColumn("ID Cliente");
                model.addColumn("Nombre");
                model.addColumn("Dirección");
                model.addColumn("Teléfono");
                tabla.setModel(model);
                for (ClienteDTO cliente : lista) {
                    Object[] datos = {cliente.getCodigoCliente(), cliente.getNombre(), cliente.getDireccion(), cliente.getTelefono()};
                    model.addRow(datos);
                }
            }
            if (combobox.getSelectedIndex() == 1) {
                model.addColumn("ID Cliente");
                model.addColumn("Nombre");
                for (ClienteDTO cliente : lista) {
                    tabla.setModel(model);
                    Object[] datos = {cliente.getCodigoCliente(), cliente.getNombre()};
                    model.addRow(datos);
                }
            }
            if (combobox.getSelectedIndex() == 2) {
                model.addColumn("ID Cliente");
                model.addColumn("Direccion");
                for (ClienteDTO cliente : lista) {
                    tabla.setModel(model);
                    Object[] datos = {cliente.getCodigoCliente(), cliente.getDireccion()};
                    model.addRow(datos);
                }
            }
            if (combobox.getSelectedIndex() == 3) {
                model.addColumn("ID Cliente");
                model.addColumn("Telefonos");
                for (ClienteDTO cliente : lista) {
                    tabla.setModel(model);
                    Object[] datos = {cliente.getCodigoCliente(), cliente.getTelefono()};
                    model.addRow(datos);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(ConsultaClienteDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        try {
            ClienteDialog cd = new ClienteDialog(null, true);
            cd.getEliminarBoton().setVisible(true);
            ClienteDTO cliente = dtaCliente.read(Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString()));
            cd.getEliminarBoton().setVisible(true);
            cd.getNombretext().setText(cliente.getNombre());
            cd.getDirecciontext().setText(cliente.getDireccion());
            cd.getTelefonotext().setText(cliente.getTelefono());
            cd.setTextAgregar("Modificar");
            cd.setClienteDTO(cliente);
            cd.setVisible(true);
            buscar();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_tablaMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaClienteDialog dialog = new ConsultaClienteDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    public ClienteDAO dtaCliente = new ClienteDAO();
    DefaultTableModel model = new DefaultTableModel();
}
