/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Gio
 */
public class MesaDialog extends javax.swing.JDialog {

    /**
     * Creates new form MesaDialog
     */
    public MesaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        localizacion = new javax.swing.JLabel();
        localizaciontext = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        localizacion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        localizacion.setForeground(new java.awt.Color(0, 0, 0));
        localizacion.setText("Localizacion:");
        jPanel1.add(localizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        localizaciontext.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        localizaciontext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizaciontextActionPerformed(evt);
            }
        });
        jPanel1.add(localizaciontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 260, 30));

        agregar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        eliminarBoton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Mesa.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localizaciontextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizaciontextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localizaciontextActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (localizaciontext.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No todos los campos estan llenos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                dtoMesa.setLocalizacion(localizaciontext.getText());
                if (agregar.getText().equals("Agregar")) {
                    JOptionPane.showMessageDialog(this, "Mesa en " + dtoMesa.getLocalizacion()
                            + " registrada.",
                            "Listo", JOptionPane.INFORMATION_MESSAGE);
                    dtaMesa.append(dtoMesa);
                    dispose();
                } else {
                    dtaMesa.update(dtoMesa);
                    JOptionPane.showMessageDialog(this, "Mesa " + dtoMesa.getCodigo_mesa()
                            + " modificada.",
                            "Listo", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        try {
            dtaMesa.delete(dtoMesa);
            JOptionPane.showMessageDialog(this, "Mesa " + dtoMesa.getCodigo_mesa()
                            + " eliminada.", "Listo", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Este mesa tiene una Reservación, no se puede elminar", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarBotonActionPerformed

    public JButton getEliminarBoton() {
        return eliminarBoton;
    }

    public void setEliminarBoton(JButton eliminarBoton) {
        this.eliminarBoton = eliminarBoton;
    }

    public JButton getAgregar() {
        return agregar;
    }

    public void setAgregar(JButton agregar) {
        this.agregar = agregar;
    }

    public JTextField getLocalizaciontext() {
        return localizaciontext;
    }

    public void setLocalizaciontext(JTextField localizaciontext) {
        this.localizaciontext = localizaciontext;
    }

    public MesaDTO getDtoMesa() {
        return dtoMesa;
    }

    public void setDtoMesa(MesaDTO dtoMesa) {
        this.dtoMesa = dtoMesa;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MesaDialog dialog = new MesaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel background;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel localizacion;
    private javax.swing.JTextField localizaciontext;
    // End of variables declaration//GEN-END:variables
    public MesaDAO dtaMesa = new MesaDAO();
    public MesaDTO dtoMesa = new MesaDTO();
}
